### Create a new report
POST http://localhost:3000/reports
content-type:application/json

{
   "make":"Honda",
   "model":"corolla",
   "year":2000,
   "mileage":100000,
   "lng":0,
   "lat":0,
   "price":500000

}



