### Create a new user
POST http://localhost:3000/auth/signup
content-type:application/json

{
    "email":"azam.khan@xord.com",
    "password":"Khan1234"
}

### Sigin a new user
POST http://localhost:3000/auth/signin
content-type:application/json

{
     "email":"azam.khan@xord.com",
    "password":"Khan1234"
}

### Find a user with ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=hk@xord.com

### Update a user
PATCH http://localhost:3000/auth/2
content-type:application/json

{
   
    "password":"Khan1234"
}

### Remove a user with ID
DELETE http://localhost:3000/auth/1

